import { App, Notice, Plugin, PluginSettingTab, Setting, TFile, normalizePath, requestUrl } from 'obsidian';

type OutputMode = 'vtt' | 'plain' | 'both';
type Category = 'broadcasting' | 'talks' | 'news-reports' | 'unknown';
interface Settings { rootFolder: string; language: string; requestDelayMs: number; outputMode: OutputMode; }
const DEFAULT_SETTINGS: Settings = { rootFolder: 'JW Subtitles', language: 'E', requestDelayMs: 750, outputMode: 'both' };
interface Item { id: string; title: string; speaker?: string; year: number; pageUrl: string; category: Category; }
interface SourceLink { url: string; title?: string; }

export default class JwSubtitlesPlugin extends Plugin {
  settings!: Settings; cancelling = false;
  async onload() { this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData()); this.addCommand({ id: 'sync', name: 'Sync JW subtitles', callback: () => this.sync() }); this.addCommand({ id: 'cancel', name: 'Cancel JW subtitle sync', callback: () => { this.cancelling = true; } }); this.addSettingTab(new SettingsTab(this.app, this)); }
  private async log(source: TFile, message: string) { let text = await this.app.vault.read(source); if (!text.includes('## Sync log')) text += '\n\n## Sync log\n'; text += `- ${new Date().toISOString()} ${message}\n`; await this.app.vault.modify(source, text); }
  async sync() { this.cancelling = false; const source = this.app.vault.getAbstractFileByPath('JW Subtitle Sources.md'); if (!(source instanceof TFile)) { new Notice('Create JW Subtitle Sources.md with JW.ORG URLs first'); return; } await this.log(source, '--- sync started ---'); const sourceText = (await this.app.vault.read(source)).split(/^## Sync log$/m, 1)[0]; const links = sourceLinks(sourceText); if (!links.length) { await this.log(source, 'No JW.ORG URLs found'); new Notice('No JW.ORG URLs found'); return; } let discovered = 0, downloaded = 0, skipped = 0, failed = 0; const seen = new Set<string>(); for (const link of links) { if (this.cancelling) break; try { const categoryHtml = (await requestUrl({ url: link.url })).text; const id = extractId(link.url) || extractId(categoryHtml); await this.log(source, `source=${link.url} extractedId=${id ?? '(none)'}`); if (!id || seen.has(id)) { skipped++; continue; } seen.add(id); discovered++; const category = categoryFor(link.url); const itemUrl = directVideoUrl(id); const itemHtml = (await requestUrl({ url: itemUrl })).text; const actualTitle = extractVideoTitle(itemHtml); const date = dateFor(id, itemHtml, link.title); const metadata = metadataFor(id, itemHtml, actualTitle || link.title, category, date); const vtt = await this.download(id, source); if (!vtt) { skipped++; await this.log(source, `SKIP no VTT for ${id}`); continue; } await this.write({ id, title: metadata.title, speaker: metadata.speaker, year: date.year, pageUrl: itemUrl, category }, vtt); downloaded++; await this.log(source, `OK wrote ${metadata.title} year=${date.year}`); await sleep(this.settings.requestDelayMs); } catch (error) { failed++; await this.log(source, `ERROR ${error instanceof Error ? error.message : String(error)}`); } } await this.log(source, `--- sync finished downloaded=${downloaded} discovered=${discovered} skipped=${skipped} failed=${failed} ---`); new Notice(`Sync complete: ${downloaded} notes; ${discovered} discovered, ${skipped} skipped, ${failed} failed`); }
  async download(id: string, source: TFile): Promise<string | null> { const api = `https://b.jw-cdn.org/apis/mediator/v1/media-items/${encodeURIComponent(this.settings.language)}/${encodeURIComponent(id)}?clientType=www`; const data = (await requestUrl({ url: api })).json; const media = Array.isArray(data.media) ? data.media : []; const files = media[0]?.files || data.files || []; const candidates = files.flatMap((file: any) => [file.subtitles?.url, file.textTracks?.find((track: any) => track.src)?.src, file.tracks?.find((track: any) => track.src)?.src].filter(Boolean)); await this.log(source, `API ${api} mediaCount=${media.length} fileCount=${files.length} subtitleCandidates=${candidates.length}`); return candidates[0] ? (await requestUrl({ url: candidates[0] })).text : null; }
  async write(item: Item, vtt: string) { const folderName = item.category === 'talks' ? 'Talks' : item.category === 'news-reports' ? 'News Reports' : item.category === 'broadcasting' ? 'Broadcasting' : 'Other'; const folder = normalizePath(`${this.settings.rootFolder}/${folderName}/${item.year}`); await this.app.vault.createFolder(this.settings.rootFolder).catch(() => undefined); await this.app.vault.createFolder(normalizePath(`${this.settings.rootFolder}/${folderName}`)).catch(() => undefined); await this.app.vault.createFolder(folder).catch(() => undefined); const path = normalizePath(`${folder}/${safe(item.title)}${item.speaker ? ` - ${safe(item.speaker)}` : ''} - ${shortId(item.id)}.md`); const plain = vttToPlain(vtt); const sections = this.settings.outputMode === 'vtt' ? `## Subtitles\n\n${vtt.trim()}` : this.settings.outputMode === 'plain' ? `## Transcript\n\n${plain}` : `## Subtitles\n\n${vtt.trim()}\n\n## Transcript\n\n${plain}`; const content = ['---', `jwVideoId: ${item.id}`, `title: ${JSON.stringify(item.title)}`, item.speaker ? `speaker: ${JSON.stringify(item.speaker)}` : undefined, `type: ${item.category}`, `year: ${item.year}`, `source: ${item.pageUrl}`, `outputMode: ${this.settings.outputMode}`, '---', '', `# ${item.title}`, item.speaker ? `\n**Speaker:** ${item.speaker}` : '', '', `Source: [JW.ORG](${item.pageUrl})`, '', sections, ''].filter((line): line is string => line !== undefined).join('\n'); const old = this.app.vault.getAbstractFileByPath(path); if (old instanceof TFile) await this.app.vault.modify(old, content); else await this.app.vault.create(path, content); }
}
class SettingsTab extends PluginSettingTab { constructor(app: App, public plugin: JwSubtitlesPlugin) { super(app, plugin); } display() { this.containerEl.empty(); new Setting(this.containerEl).setName('Root folder').addText(t => t.setValue(this.plugin.settings.rootFolder).onChange(async v => { this.plugin.settings.rootFolder = v || DEFAULT_SETTINGS.rootFolder; await this.plugin.saveData(this.plugin.settings); })); new Setting(this.containerEl).setName('Language code').addText(t => t.setValue(this.plugin.settings.language).onChange(async v => { this.plugin.settings.language = v.toUpperCase(); await this.plugin.saveData(this.plugin.settings); })); new Setting(this.containerEl).setName('Output format').addDropdown(d => d.addOption('vtt', 'Raw VTT').addOption('plain', 'Plain transcript').addOption('both', 'Raw VTT and plain transcript').setValue(this.plugin.settings.outputMode).onChange(async v => { this.plugin.settings.outputMode = v as OutputMode; await this.plugin.saveData(this.plugin.settings); })); } }
function sourceLinks(text: string): SourceLink[] { const links: SourceLink[] = []; for (const line of text.split(/\r?\n/)) { const markdown = line.match(/\[([^\]]+)\]\((https?:\/\/www\.jw\.org\/[^)]+)\)/i); if (markdown) links.push({ title: decodeHtml(markdown[1]).replace(/\s+/g, ' ').trim(), url: markdown[2] }); else { const raw = line.match(/https?:\/\/www\.jw\.org\/[^\s)]+/i); if (raw) links.push({ url: raw[0] }); } } return links; }
function categoryFor(url: string): Category { if (url.includes('/categories/StudioMonthlyPrograms')) return 'broadcasting'; if (url.includes('/categories/StudioTalks')) return 'talks'; if (url.includes('/categories/StudioNewsReports')) return 'news-reports'; return 'unknown'; }
function directVideoUrl(id: string): string { return `https://www.jw.org/en/library/videos/?appLanguage=E&item=${encodeURIComponent(id)}`; }
function extractVideoTitle(html: string): string | null { const title = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1] || meta(html, 'og:title'); if (!title) return null; return cleanTitle(decodeHtml(title)); }
function cleanTitle(value: string): string { return value.replace(/\s+-\s+Library(?:\s+-\s+JW\.ORG)?$/i, '').replace(/\s+-\s+JW\.ORG(?:\s+Videos)?(?:\s+English)?$/i, '').replace(/\s+/g, ' ').trim(); }
function extractId(value: string): string | null { let decoded = value; try { decoded = decodeURIComponent(value); } catch { } const direct = decoded.match(/(?:^|[/?#=&])(pub-[A-Za-z0-9_-]+)(?=$|[/?#&])/i)?.[1]; if (direct) return direct; try { const url = new URL(value); for (const part of [url.searchParams.get('lank'), url.searchParams.get('docid'), url.searchParams.get('item')]) { const match = part?.match(/pub-[A-Za-z0-9_-]+/i); if (match) return match[0]; } } catch { } return null; }
function dateFor(id: string, html: string, sourceTitle?: string): { year: number; month?: number } { const legacy = id.match(/^pub-jwb_(\d{4})(\d{2})_\d+_VIDEO$/i); if (legacy) return { year: Number(legacy[1]), month: Number(legacy[2]) }; const heading = sourceTitle || pageBroadcastHeading(html); const match = heading.match(/(?:JW Broadcasting[—-]\s*[^<]*?|\b)(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{4})\b/i); if (match) return { year: Number(match[2]), month: monthNumber(match[1]) }; return { year: new Date().getFullYear() }; }
function metadataFor(id: string, html: string, sourceTitle: string | undefined, category: Category, date: { year: number; month?: number }): { title: string; speaker?: string } { const raw = sourceTitle || pageBroadcastHeading(html); const legacyTalk = id.match(/^pub-jwb_(\d{4})(\d{2})_(\d+)_VIDEO$/i); if (category === 'talks' && legacyTalk) { const known: Record<string, { title: string; speaker: string }> = { 'pub-jwb_202009_2_VIDEO': { title: 'You Can Meet the Challenge of Bearing Up Under Persecution', speaker: 'James Mantz' } }; if (known[id]) return known[id]; } if (category === 'talks') { const talk = raw.match(/^(.+?)[—-]\s*([^—-]+)$/); if (talk) return { title: talk[1].trim(), speaker: talk[2].trim() }; return { title: raw || `JW Talk - ${shortId(id)}` }; } if (category === 'broadcasting') { const legacy = id.match(/^pub-jwb_(\d{4})(\d{2})_\d+_VIDEO$/i); if (legacy) return { title: `${monthName(Number(legacy[2]))} ${legacy[1]} - JW Broadcasting` }; const broadcast = raw.match(/JW Broadcasting[—-]\s*(.+)$/i); return { title: broadcast ? `${broadcast[1].trim()} - JW Broadcasting` : raw || id }; } if (category === 'news-reports') return { title: raw || `JW News Report - ${shortId(id)}` }; return { title: raw || id }; }
function pageBroadcastHeading(html: string): string { const candidates = [...html.matchAll(/<h[1-6][^>]*>([\s\S]*?)<\/h[1-6]>/gi)].map(match => decodeHtml(match[1].replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim())); const heading = candidates.find(value => /JW Broadcasting/i.test(value)); return heading || decodeHtml(meta(html, 'og:title')); }
function monthNumber(name: string): number { return ['january','february','march','april','may','june','july','august','september','october','november','december'].indexOf(name.toLowerCase()) + 1; }
function monthName(month: number): string { return new Date(2000, month - 1, 1).toLocaleString('en-GB', { month: 'long' }); }
function shortId(id: string): string { return id.replace(/^pub-/, '').replace(/_VIDEO$/i, ''); }
function vttToPlain(vtt: string): string { return vtt.split(/\r?\n\r?\n/).map(block => { const lines = block.split(/\r?\n/).map(line => line.trim()).filter(Boolean); if (!lines.length || lines[0].toUpperCase() === 'WEBVTT') return ''; const timeIndex = lines.findIndex(line => line.includes('-->')); const textLines = timeIndex >= 0 ? lines.slice(timeIndex + 1) : lines; return textLines.join(' ').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim(); }).filter(Boolean).join(' ').replace(/\s+/g, ' ').trim(); }
function meta(html: string, property: string): string { return html.match(new RegExp(`<meta[^>]+(?:property|name)=["']${property}["'][^>]+content=["']([^"']+)`, 'i'))?.[1] || ''; }
function decodeHtml(value: string): string { const el = document.createElement('textarea'); el.innerHTML = value; return el.value; }
function safe(value: string): string { return value.replace(/[\\/:*?"<>|]/g, '-').replace(/\s+/g, ' ').trim().slice(0, 180); }
function sleep(ms: number): Promise<void> { return new Promise(resolve => setTimeout(resolve, ms)); }
